language: python
python: "3.8"
node_js: "12"
cache:
  directories:
  - $HOME/.pipenv
  - node_modules
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$(pwd)
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
    - WORKON_HOME=$HOME/.cache/venvs
install:
  make init
script:
  make integration
after_success:
  - bash <(curl -s https://codecov.io/bash) -y .ci/codecov.yml
