language: python
python: "3.8"
before_install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)
install: |
  sudo pip install pipenv
  pipenv install --dev
script:
  make integration
after_success:
  - bash <(curl -s https://codecov.io/bash)
