language: python
python: "3.8"
node_js: "12"
branches:
  # avoid duplicate jobs on updated PRs
  only:
    - master
cache:
  directories:
  - $HOME/.cache
  - node_modules
env:
  global:
    - PYTHONPATH=$PYTHONPATH:$(pwd)
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIP_CACHE_DIR=$HOME/.cache/pip
    - PIPENV_CACHE_DIR=$HOME/.cache/pipenv
    - WORKON_HOME=$HOME/.cache/venvs
install:
  make init
script:
  pipenv run make integration
after_success:
  - bash <(curl -s https://codecov.io/bash) -y .ci/codecov.yml
  - >
    test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_PULL_REQUEST = "false" &&
    pipenv run make deploy-app
