app: pogam

service: pogam-shared-resources

custom: ${file(../serverless.common.yml):custom}

package: ${file(../serverless.common.yml):package}

provider:
  name: aws
  stage: "${self:custom.stage}"
  memorySize: 128

resources:
  Description: "CloudFormation template for Pogam's shared resources."

  Parameters:
    AuroraClusterName:
      Description: "Aurora RDS cluster name"
      Type: String
      Default: "${self:custom.stage}PogamDB"

    AuroraDatabaseName:
      Description: "Aurora RDS database name"
      Type: String
      Default: pogam

    AuroraUserName:
      AllowedPattern: "[a-zA-Z0-9_]+"
      ConstraintDescription: must be between 1 to 32 alphanumeric characters.
      Description:
        The database admin account user name, between 1 to 32 alphanumeric characters.
      MaxLength: '32'
      MinLength: '1'
      Type: String
      Default: pogam_db_admin_user

  Resources:
    AuroraCredentials:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: "${self:custom.stage}AuroraCredentialsSecret"
        Description: RDS database auto-generated credentials
        GenerateSecretString:
          SecretStringTemplate: '{"username": "#{AuroraUserName}"}'
          GenerateStringKey: "password"
          PasswordLength: 30
          ExcludeCharacters: '"@/\'

    AuroraCluster:
      Type: AWS::RDS::DBCluster
      Properties:
        DBClusterIdentifier: !Ref AuroraClusterName
        MasterUsername:
          Fn::Join:
            - ""
            - - "{{resolve:secretsmanager:"
              - !Ref AuroraCredentials
              - ":SecretString:username}}"
        MasterUserPassword:
          Fn::Join:
            - ""
            - - "{{resolve:secretsmanager:"
              - !Ref AuroraCredentials
              - ":SecretString:password}}"
        DatabaseName: !Ref AuroraDatabaseName
        Engine: aurora-postgresql
        EngineMode: serverless
        ScalingConfiguration:
          AutoPause: true
          MaxCapacity: 2
          MinCapacity: 2
          SecondsUntilAutoPause: 300
        EnableHttpEndpoint: true
        StorageEncrypted: true
        BackupRetentionPeriod: 7

    PhotosBucket:
      Type: AWS::S3::Bucket

    ApiGatewayRestApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: pogam-api
        Description: Pogam's API Gateway

    RestApiVersion1Resource:
      Type: AWS::ApiGateway::Resource
      Properties:
        RestApiId: { Ref: "ApiGatewayRestApi" }
        ParentId: { Fn::GetAtt: "ApiGatewayRestApi.RootResourceId" }
        PathPart: v1

    CognitoUserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:custom.stage}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email

    CognitoUserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:custom.stage}-user-pool-client
        UserPoolId:
          Ref: CognitoUserPool
        ExplicitAuthFlows:
          - ADMIN_NO_SRP_AUTH
        GenerateSecret: false

    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: "${self:custom.stage}IdentityPool"
        AllowUnauthenticatedIdentities: false
        CognitoIdentityProviders:
          - ClientId:
              Ref: CognitoUserPoolClient
            ProviderName:
              Fn::GetAtt: ["CognitoUserPool", "ProviderName"]

    CognitoIdentityPoolRoles:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: ["CognitoAuthRole", "Arn"]

    CognitoAuthRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /
        AssumeRolePolicyDocument:
          Statement:
            - Effect: 'Allow'
              Principal:
                Federated: 'cognito-identity.amazonaws.com'
              Action:
                - 'sts:AssumeRoleWithWebIdentity'
              Condition:
                StringEquals:
                  'cognito-identity.amazonaws.com:aud':
                    Ref: CognitoIdentityPool
                'ForAnyValue:StringLike':
                  'cognito-identity.amazonaws.com:amr': authenticated
        Policies:
          - PolicyName: 'CognitoAuthorizedPolicy'
            PolicyDocument:
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 'mobileanalytics:PutEvents'
                    - 'cognito-sync:*'
                    - 'cognito-identity:*'
                  Resource: '*'

                # Allow users to invoke our API
                - Effect: 'Allow'
                  Action:
                    - 'execute-api:Invoke'
                  Resource:
                    Fn::Join:
                      - ''
                      -
                        - 'arn:aws:execute-api:'
                        - Ref: AWS::Region
                        - ':'
                        - Ref: AWS::AccountId
                        - ':'
                        - Ref: ApiGatewayRestApi
                        - '/*'

  Outputs:
    AuroraClusterArn:
      Description: "ARN of the Aurora database cluster."
      Value:
        Fn::Join:
          - ""
          - - "arn:aws:rds:#{AWS::Region}:#{AWS::AccountId}:cluster:"
            - !Ref AuroraClusterName
      Export:
        Name: "${self:custom.stage}AuroraClusterArn"

    AuroraSecretArn:
      Description: "ARN of the secret containing the Aurora database's credentials."
      Value: !Ref AuroraCredentials
      Export:
        Name: "${self:custom.stage}AuroraSecretArn"

    AuroraDatabaseName:
      Description: Pogam's database name within the Aurora database cluster.
      Value: !Ref AuroraDatabaseName
      Export:
        Name: "${self:custom.stage}AuroraDatabaseName"

    PhotosBucketName:
      Description: "Name of the S3 bucket used to store listings' photos."
      Value:
        Ref: PhotosBucket
      Export:
        Name: "${self:custom.stage}PhotosBucketName"

    PhotosBucketArn:
      Description: "ARN of the S3 bucket used to store listings' photos."
      Value:
        Fn::GetAtt:
          - PhotosBucket
          - Arn
      Export:
        Name: "${self:custom.stage}PhotosBucketArn"

    ApiGatewayRestApiId:
      Description: "The resource ID of the API Gateway."
      Value:
        Ref: ApiGatewayRestApi
      Export:
        Name: "${self:custom.stage}ApiGatewayRestApiId"

    RestApiRootResource:
      Description: "The root resource of the API Gateway."
      Value:
          Fn::GetAtt:
            - ApiGatewayRestApi
            - RootResourceId
      Export:
        Name: "${self:custom.stage}RestApiRootResource"

    RestApiVersion1Resource:
      Description: "The /v1 resource of the API Gateway."
      Value:
        Ref: RestApiVersion1Resource
      Export:
        Name: "${self:custom.stage}RestApiVersion1Resource"

    UserPoolId:
      Description: "The id of the User Pool."
      Value:
        Ref: CognitoUserPool
      Export:
        Name: "${self:custom.stage}UserPoolId"

    UserPoolClientId:
      Description: "The id of the User Pool Client."
      Value:
        Ref: CognitoUserPoolClient
      Export:
        Name: "${self:custom.stage}UserPoolClientId"

    IdentityPoolId:
      Description: "The id of the User Identity Pool."
      Value:
        Ref: CognitoIdentityPool
      Export:
        Name: "${self:custom.stage}IdentityPoolId"


plugins:
  - serverless-pseudo-parameters
