name: pogam
dependencies:
  - python=3.8
  - pip:
    - black==19.3b0
    - beautifulsoup4==4.8.1
    - click==7.0
    - click-log==0.3.2
    - fake-useragent==0.1.11
    - flake8==3.7.8
    - flask==1.1.1
    - flask-sqlalchemy==2.4.1
    - mypy==0.740
    - pytest==5.2.2
    - pytest-cov==2.8.1
    - requests==2.22.0
    - sphinx==2.2.1
    - sphinx-autobuild==0.7.1
    - sphinx_rtd_theme==0.4.3
    - sqlalchemy==1.3.10
    - sqlalchemy-aurora-data-api==0.1.4
