"""Tweak constraints

Revision ID: 9479aaac5ade
Revises: c944d2fca6e1
Create Date: 2019-12-17 19:56:17.437621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9479aaac5ade"
down_revision = "c944d2fca6e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("properties", "type_id", existing_type=sa.INTEGER(), nullable=False)
    op.drop_constraint(
        "fk_properties_heating_id_heating_types", "properties", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_properties_kitchen_id_kitchen_types", "properties", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_properties_type_id_property_types", "properties", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_properties_type_id_property_types"),
        "properties",
        "property_types",
        ["type_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_properties_heating_id_heating_types"),
        "properties",
        "heating_types",
        ["heating_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    op.create_foreign_key(
        op.f("fk_properties_kitchen_id_kitchen_types"),
        "properties",
        "kitchen_types",
        ["kitchen_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_properties_kitchen_id_kitchen_types"), "properties", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_properties_heating_id_heating_types"), "properties", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_properties_type_id_property_types"), "properties", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_properties_type_id_property_types",
        "properties",
        "property_types",
        ["type_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_properties_kitchen_id_kitchen_types",
        "properties",
        "kitchen_types",
        ["kitchen_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_properties_heating_id_heating_types",
        "properties",
        "heating_types",
        ["heating_id"],
        ["id"],
        onupdate="CASCADE",
        ondelete="CASCADE",
    )
    op.alter_column("properties", "type_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
