app: pogam

service: pogam-scrape-schedules-api

custom: ${file(../serverless.common.yml):custom}

package: ${file(../serverless.common.yml):package}

provider:
  name: aws
  runtime: python3.8
  memorySize: 128
  iamRoleStatements:
    - Effect: Allow
      Action: "events:*"
      Resource: "*"
  apiGateway:
    restApiId:
      Fn::ImportValue: "${self:custom.stage}ApiGatewayRestApiId"
    restApiRootResourceId:
      Fn::ImportValue: "${self:custom.stage}RestApiRootResource"
    restApiResources:
      /v1:
        Fn::ImportValue: "${self:custom.stage}RestApiVersion1Resource"
  environment:
    AWS_DEFAULT_REGION: "#{AWS::Region}"

functions:
  create:
    handler: handlers.create
    events:
      - http:
          path: v1/scrape-schedules
          method: post
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Fn::ImportValue: "${self:custom.stage}ApiGatewayAuthorizerId"
    environment:
      STAGE: "${self:custom.stage}"
      PROXY11_API_KEY: "${ssm:/pogam/proxy11/token~true}"
      SCRAPE_FUNCTION_ARN:
        Fn::ImportValue: "${self:custom.stage}ScrapeFunctionArn"

  list:
    handler: handlers.list_
    events:
      - http:
          path: v1/scrape-schedules
          method: get
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Fn::ImportValue: "${self:custom.stage}ApiGatewayAuthorizerId"
    environment:
      STAGE: "${self:custom.stage}"

  delete:
    handler: handlers.delete
    events:
      - http:
          path: v1/scrape-schedules/{rule_name}
          method: delete
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Fn::ImportValue: "${self:custom.stage}ApiGatewayAuthorizerId"
    environment:
      STAGE: "${self:custom.stage}"

resources:
  Description: "CloudFormation template for Pogam's scrape scheduling service."

  Resources:
    ScrapeFunctionResourcePolicy:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:InvokeFunction
        FunctionName:
          Fn::ImportValue: "${self:custom.stage}ScrapeFunctionArn"
        Principal: events.amazonaws.com
        SourceArn:
          Fn::Sub: 'arn:aws:events:#{AWS::Region}:#{AWS::AccountId}:rule/*'


plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
